### ISSUE TITLE
Could not find Eigen3 when configuring Tudat, eigen folder is empty

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudatBundle#13]
Hi,

I'm setting up Tudat on Windows 10 and put the tudatBundle on the D drive.
When configuring Tudat, I get the following error message in the General Messages box of Qt Creator:

Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_OK )

The full output is:

------------------------------------------------------------------------
Running "C:\Program Files\CMake\bin\cmake.exe D:/tudatBundle_mvdb "-GCodeBlocks - MinGW Makefiles" "-DCMAKE_CXX_COMPILER:STRING=C:/Qt/Tools/mingw492_32/bin/g++.exe" "-DCMAKE_C_COMPILER:STRING=" "-DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}" "-DQT_QMAKE_EXECUTABLE:STRING="" in D:\tudatBundle_mvdb-build.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/Qt/Tools/mingw492_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw492_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw492_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw492_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake modules: D:/tudatBundle_mvdb/external/CMake/
-- D:/tudatBundle_mvdb
-- BOOST: Using gnu.
-- Build boost (note that this may take a while, please sit back)
--   .\b2.exe;--user-config=cmake-config.jam;link=static,shared;threading=multi;--build-dir=Build;stage;-sNO_BZIP2=1;variant=release;--layout=tagged;toolset=gcc;--with-filesystem;--with-system;--with-thread;--with-regex;--with-date_time;--with-test
-- Building CSpice from within TudatBundle.
-- WARNING: building release version!
-- Building Tudat from within TudatBundle.
-- Tudat Relative path (wrt to project): /tudat/Tudat
-- WARNING: building release version!
-- Using gnucxx compiler.
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Success
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "2.91.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  tudat/Tudat/External/CMake/FindEigen3.cmake:79 (find_package_handle_standard_args)
  tudat/Tudat/CMakeLists.txt:122 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/tudatBundle_mvdb-build/CMakeFiles/CMakeOutput.log".
*** cmake process exited with exit code 1.

----------------------------------------------------------------------------

The CMakeOutput.log can be checked [here](https://github.com/Tudat/tudatBundle/files/851096/CMakeOutput.txt).

I already tried adding the FindEigen3.cmake file manually to the D:\tudatBundle_mvdb\external\CMake directory, but that did not resolve the issue. I'm using MinGW 4.9.2.

How can this issue be resolved?

Thanks,

Michael

**Comment by magnific0** [comment]
I don't think the drive letter matters. Nor think that any cmake file are/were missing. Can you check whether the eigen folder is present and not empty?

I'm surprised by this error as eigen usually doesn't give us any trouble.

Cheers!

**Comment by mvandenbroeck** [comment]
Yes indeed, the Eigen folder inside my tudatBundle is empty. I thought the content of Eigen would be downloaded during the configuration, just like boost.
I didn't clone the official TudatBundle, but my personal TudatBundle from gitHub. So I should check that I have the correct version on my pc.

Thanks for pointing this out.

Michael

**Comment by magnific0** [comment]
The eigen guys have a tendency to remove commits from their history, breaking the submodule pointer (defined in .gitmodules, visualized by @sum on your tudatBundle repo GH page). We have recenly updated to point upstream tudatBundle to a release tag of Eigen, hoping this is more stable. 

So it's best to update tudatBundle from the upstream to also get this and other new changes
