### ISSUE TITLE
Errors when configuring Tudat: boost_python, cannot find Tudat

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudatBundle#14]
Hi,

I get the following output when configuring Tudat on Windows 10:

---------------------------------------------------------------------------
Running Windows Runtime device detection.
No winrtrunner.exe found.
Running "C:\Program Files\CMake\bin\cmake.exe D:/tudatBundle_mvdb "-GCodeBlocks - MinGW Makefiles" "-DCMAKE_CXX_COMPILER:STRING=C:/Qt/Tools/mingw492_32/bin/g++.exe" "-DCMAKE_C_COMPILER:STRING=" "-DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}" "-DQT_QMAKE_EXECUTABLE:STRING="" in D:\tudatBundle_mvdb-build.
-- CMake modules: D:/tudatBundle_mvdb/external/CMake/
-- D:/tudatBundle_mvdb
-- BOOST: Using gnu.
-- Build boost (note that this may take a while, please sit back)
--   .\b2.exe;--user-config=cmake-config.jam;link=static,shared;threading=multi;--build-dir=Build;stage;-sNO_BZIP2=1;variant=release;--layout=tagged;toolset=gcc;--with-filesystem;--with-system;--with-thread;--with-regex;--with-date_time;--with-test
-- Building CSpice from within TudatBundle.
-- WARNING: building release version!
-- Building Tudat from within TudatBundle.
-- Tudat Relative path (wrt to project): /tudat/Tudat
-- WARNING: building release version!
-- Using gnucxx compiler.
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   date_time
--   system
--   unit_test_framework
--   filesystem
--   regex
-- SPICE enabled!
-- SPICE_LIBRARIES: cspice
-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- GSL disabled!
-- Building USMPropagation from within TudatBundle.
-- Relative path (wrt to project): /Thesis
-- WARNING: building release version!
-- Using gnucxx compiler.
CMake Error at Thesis/CMakeModules/FindBoost.cmake:1200 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.53.0

  Boost include path: D:/tudatBundle_mvdb/boost

  The following Boost libraries could not be found:

          boost_serialization
          boost_chrono
          boost_atomic
          boost_python

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  Thesis/CMakeLists.txt:164 (find_package)

CMake Error at Thesis/CMakeModules/FindTudat.cmake:52 (file):
  file failed to open for reading (No such file or directory):

    D:/tudatBundle_mvdb/Thesis/TUDAT_BASE_PATH-NOTFOUND/../Tudat/tudatVersion.h
Call Stack (most recent call first):
  Thesis/CMakeModules/FindTudat.cmake:99 (_tudat_check_version)
  Thesis/CMakeLists.txt:176 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Tudat (missing: TUDAT_VERSION_OK) (Required is at least
  version "2.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  Thesis/CMakeModules/FindTudat.cmake:103 (find_package_handle_standard_args)
  Thesis/CMakeLists.txt:176 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/tudatBundle_mvdb-build/CMakeFiles/CMakeOutput.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= 
CMAKE_C_COMPILER= 
CMAKE_C_COMPILER= 
CMAKE_C_COMPILER= 

CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_MAKE_PROGRAM
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_MAKE_PROGRAM
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_MAKE_PROGRAM
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_MAKE_PROGRAM
-- Generating done
-- Build files have been written to: D:/tudatBundle_mvdb-build
*** cmake process exited with exit code 1.

------------------------------------------------------------------------------------

Here is the [CMakeLists.txt](https://github.com/Tudat/tudatBundle/files/853293/CMakeLists.txt) I'm using.
Here is the [CMakeOutput.txt](https://github.com/Tudat/tudatBundle/files/853310/CMakeOutput.txt).

How can these errors be resolved?
For the Boost error I guess I'll have to build Boost manually according to the Tudat manual. But what about 'Could not find Tudat' and the other errors.?

I can also try to remove the TudatBundle again and download the official TudatBundle instead of my forked TudatBundle. But I prefer having the exact same copy of Tudat as the one I was using on my old laptop.

Kind regards,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

The four libraries its missing happen to be exactly the ones needed for pagmo. I don't see them in the b2 command way at the top, so I'm guessing that your USE_PAGMO and USE_PYGMO are OFF. If you change then to on in your CMakeCache, it should compile the additional boost libraries automatically,

Cheers,

Dominic

**Comment by mvandenbroeck** [comment]
You're right. USE_PAGMO was off and I updated the CMakeLists.txt so that I now have the USE_PYGMO option. I set both options to on, but it still get an error for BoostPythonExe which is not set to my python executable.

The full output is:

--------------------------------------
Running Windows Runtime device detection.
No winrtrunner.exe found.
Running "C:\Program Files\CMake\bin\cmake.exe D:/tudatBundle_mvdb "-GCodeBlocks - MinGW Makefiles" "-DCMAKE_CXX_COMPILER:STRING=C:/Qt/Tools/mingw492_32/bin/g++.exe" "-DCMAKE_C_COMPILER:STRING=" "-DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}" "-DQT_QMAKE_EXECUTABLE:STRING="" in C:\Users\Michael\AppData\Local\Temp\qtc-cmake-rkRYii.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/Qt/Tools/mingw492_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw492_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw492_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw492_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- D:/tudatBundle_mvdb
-- BOOST: Using gnu.
-- Downloading boost 1.53.0 to C:/Users/Michael/AppData/Local/Temp/qtc-cmake-rkRYii
-- [download 100% complete]
-- [download 0% complete]
-- [download 1% complete]
...
-- [download 99% complete]
-- [download 100% complete]
-- Extracting boost 1.53.0 to C:/Users/Michael/AppData/Local/Temp/qtc-cmake-rkRYii/boost_unzip
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) 
CMake Error at external/CMake/add_boost.cmake:204 (message):
  Please set the BoostPythonExe variable to your Python executable.
Call Stack (most recent call first):
  CMakeLists.txt:57 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Michael/AppData/Local/Temp/qtc-cmake-rkRYii/CMakeFiles/CMakeOutput.log".
*** cmake process exited with exit code 1.

------------------------------------------------------------------

How should I set the BoostPythonExe variable to my Python executable?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
I'm guessing that this indicates that python is not installed (or at least not in your path). Are you using Pyhton/Pygmo?

**Comment by mvandenbroeck** [comment]
No I'm not using Python or PyGMO.

Actually I don't need PaGMO anymore either. That's why I set them to OFF in the CMakeListst.txt before.
I don't have a CMakeCache at the moment. I deleted it earlier to try a clean configuration.

**Comment by DominicDirkx** [comment]
Then you don't need boost_python, I think. Why is it requesting it?

**Comment by mvandenbroeck** [comment]
Hi,

I deleted the entire tudatBundle from my computer and cloned the official master tudatBundle from GitHub. 
For the tudatBundle/tudat I checked out at my personal tudat branch.

I was able to configure this successfully for the following four settings:
USE_PAGMO OFF
USE_PYGMO OFF

USE_PAGMO ON
USE_PYGMO OFF

USE_PAGMO OFF
USE_PYGMO ON

USE_PAGMO ON
USE_PYGMO ON

Next, I cloned my Thesis folder (containing all the C++ files for thesis project) and stored it under tudatBundle/Thesis.
I included my Thesis folder to the project by adding `add_subdirectory( "${PROJECTROOT}/Thesis/")` to the tudatBundle/CMakeLists.txt.
I commented out every part in Thesis/CMakeLists.txt that refers to PaGMO or PyGMO.

When running CMake again, it gives an error for all of the possible PAGMO/PYGMO settings. The error is the same every time and reads:

----------------------------------------------------------------
Unable to find the requested Boost libraries. Boost version: 1.53.0 Boost include path: D:/tudatBundle_mvdb/boost
The following Boost libraries could not be found: boost_python
Some (but not all) of the required Boost libraries were found.
You may need to install these additional Boost libraries. 
Alternatively, set BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT to the location of Boost.
Thesis/CMakeLists.txt:164 (find_package)

---------------------------------------------------------------------

The entire output can be found [here](https://github.com/Tudat/tudatBundle/files/859144/OutputOfIssue1.txt).

Apparantly, line 164 of Thesis/CMakeLists.txt is a problem. The line reads:

`find_package(Boost 1.45.0 
            COMPONENTS thread date_time system unit_test_framework filesystem regex serialization chrono atomic python REQUIRED)`

I tried changing into:

`find_package(Boost 1.53.0 
            COMPONENTS thread date_time system unit_test_framework filesystem regex serialization chrono atomic python REQUIRED)`

since 1.53.0 is the boost version that is specified in tudatBundle/CMakeLists.txt. This didn't solve the error.

I also tried putting the USE_PAGMO option to OFF in the CMakeCache. This didn't solve the error.

Any ideas on how to fix these errors?
I cannot continue working on my Thesis project without having solved this issue.

Thanks,

Michael

**Comment by DominicDirkx** [comment]
I think you answered your own question without knowing it. The line you show says that boost python is required. Remove python from the list of required libraries and try again.

**Comment by mvandenbroeck** [comment]
Thanks, this indeed solves the python-library related error.

Now, I'm still getting the following error messages:


`file failed to open for reading (No such file or directory):
D:/tudatBundle_mvdb/Thesis/TUDAT_BASE_PATH-NOTFOUND/.../Tudat/tudatVersion.h
Thesis/CMakeModules/FindTudat.cmake:99
(_tudat_check_version) Thesis/CMakeLists.txt:176 (find_package)`

and

`Could NOT find Tudat (missing: TUDAT_VERSION_OK)
(Required is at least version "2.0")
C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377
(_FPHSA_FAILURE_MESSAGE)
Thesis/CMakeModules/FindTudat.cmake:103 (find_package_handle_standard_args)
Thesis/CMakeLists.txt: 176 (find_package)`

Line 176 of Thesis/CMakeLists.txt reads:

`find_package(Tudat 2.0 REQUIRED)`

The file tudatVersion.h is present in tudatBundle_mvdb/tudat/Tudat/. But for some reason, it looks like CMake is searching for the file inside tudatBundle_mvdb/Thesis. How can I make sure the Tudat package is found?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Could you provide a link to the FindTudat script that you are using, and the CMakeLists file used in 'Thesis'?

**Comment by mvandenbroeck** [comment]
Yeah sure, here they are:

[CMakeLists.txt](https://github.com/Tudat/tudatBundle/files/861395/CMakeLists.txt)


[FindTudat.txt](https://github.com/Tudat/tudatBundle/files/861404/FindTudat.txt)

**Comment by DominicDirkx** [comment]
Try this one
[FindTudat.txt](https://github.com/Tudat/tudatBundle/files/861429/FindTudat.txt)

**Comment by mvandenbroeck** [comment]
Yes! This works!

Thanks a lot!

Michael

**Comment by DominicDirkx** [comment]
Good to hear. You had placed the 'Thesis' folder one layer closer to the bundle folder than previously, which prevented the findTudat script from finding the library.
