### ISSUE TITLE
Problem with .DS_Store file

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudatBundle#17]
When trying to run CMake (for the first time), I got an error at [add_boost.cmake::215](../blob/master/external/CMake/add_boost.cmake#L215), because it is checking that the extracted directory has only one file (directory), but in my case it contained too, since a .DS_Store file was also there.

I found a temporary fix it by changing the line in my fork from
```
  if(NOT n EQUAL "1" OR NOT IS_DIRECTORY ${ExtractedDir})
```
to
```
  if(NOT IS_DIRECTORY ${ExtractedDir})
```
but maybe a better (although more complex) fix could be checking that the number of files not starting with "." is 1.

**Comment by DominicDirkx** [comment]
Could you post the exact error that you are getting?

**Comment by aleixpinardell** [comment]
The problem only happened once, apparently it's not happening anymore. So I guess we can close the issue as I cannot reproduce the problem.
