### ISSUE TITLE
Step 3.3

### ISSUE THREAD

**Issue by vaycavi** [Tudat/tudatBundle#22]
I obtain errors in Qt creator in "Configure Tudat Libraries, step 3". This is the error I obtain:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory C:/Users/Vicente/repos/num_astro/tudat/Tudat

And then a lot of lines with directories appear.

How can I solve this in order to build the file? 
Thank you

**Comment by DominicDirkx** [comment]
@vaycartavila This most likely stems from the fact that the path is too long. See the note given here:

http://tudat.tudelft.nl/installation/downloadTudatBundle/smartgitDeveloper.html#clone-the-tudat-bundle

Make sure to clone the tudatBundle from github directly into C:/

**Comment by DominicDirkx** [comment]
@vaycartavila Could you let us know if your issue has been resolved now? Thank.

**Comment by vaycavi** [comment]
Yes, I cloned the tudatBundle directly into C:/ and it worked. Thank you.
