### ISSUE TITLE
GitHub academic discount coupon expired

### ISSUE THREAD

**Issue by janwillemarink** [Tudat/tudatBundle#23]
Dear,

I already went through step 1-4 of the installation guide and everything worked for me. However, I just tried to log in to my GitHub account and a message appears saying that my GitHub academic discount coupon has expired (meaning that I also do not have access to my private repository anymore). What should I do now?

Best regards,
Jan-Willem
<img width="1440" alt="schermafbeelding 2017-11-16 om 21 30 11" src="https://user-images.githubusercontent.com/33624827/32914399-c2626df8-cb15-11e7-9ef0-892dbf27f2f0.png">

**Comment by magnific0** [comment]
Have you tried re-applying? My account has been good for a couple of years now.

**Comment by DominicDirkx** [comment]
Also: have you used tour TU Delft account for registering on Github?

**Comment by janwillemarink** [comment]
I have re-applied three times yesterday, did not work. I did use my TU Delft mail. 
Fortunately, I re-applied again today and this time it worked, so everything is good!
Thanks for both replies though!
