### ISSUE TITLE
add_boost/QT compatibility (on Mac?)

### ISSUE THREAD

**Issue by transferorbit** [Tudat/tudatBundle#27]
### How to get QT to configure with boost in the latest build?
[This earlier issue](https://github.com/Tudat/tudatBundle/issues/8) has either resurfaced, or something else is afoot.
- After doing a clean install of tudatBundle, QT throws the following, boost-related error during configuration:
> `BOOST: Using clang.`
> `Extracting boost 1.64.0 to /Users/kevin/tudatBundle/boost/build/boost_unzip`
>  `Building b2 (bjam)`
>   `./bootstrap.sh;--with-toolset=clang`
>  `CMake Error at external/CMake/add_boost.cmake:320 (message):`
>   `Failed running bootstrap:`
>   `Building Boost.Build engine with toolset clang...`
>   `Failed to build Boost.Build build engine`
>   `Consult 'bootstrap.log' for more details`
>   `Call Stack (most recent call first):`
>   `CMakeLists.txt:61 (include)`
>   `Configuring incomplete, errors occurred!`
>   `See also "/var/folders/wm/m90p1gjn4d51_tk0sv79rw5m0000gn/T/QtCreator-y8BzSn/qtc-cmake-oImck8vR/CMakeFiles/CMakeOutput.log”.`
>  `CMake Project parsing failed.`

- Under the _Issues_ tab in QT, the following _Issue_ is produced:
>`/Users/kevin/tudatBundle/external/CMake/add_boost.cmake:320: error: Failed running bootstrap: 
> Building Boost.Build engine with toolset clang... Failed to build Boost.Build build engine Consult 
> 'bootstrap.log' for more details`

- I attempted [manual installation](http://tudat.tudelft.nl/installation/troubleshooting/compilingBoostManually.html) of boost libraries, but this also produces errors:
The following command appears to complete successfully:
> ` ./bootstrap.sh –with-toolset=clang`
> `Building Boost.Build engine with toolset darwin... tools/build/src/engine/bin.macosxx86_64/b2`
> `Detecting Python version... 2.7`
> `Detecting Python root... /System/Library/Frameworks/Python.framework/Versions/2.7`
> `Unicode/ICU support for Boost.Regex?... not found.`
> `Backing up existing Boost.Build configuration in project-config.jam.1`
> `Generating Boost.Build configuration in project-config.jam...`
> 
> `Bootstrapping is done. To build, run:`
>  `  ./b2`
>    
> `To adjust configuration, edit 'project-config.jam’.`
> `Further information:`
>   `Command line help:`
>     `./b2 --help`
>   `Getting started guide: `
>    `http://www.boost.org/more/getting_started/unix-variants.html`
>   `Boost.Build documentation:`
>    `http://www.boost.org/build/doc/html/index.html`

 However, the command `.bootstrap.bat clang` aka `./bootstrap.bat clang` cannot be run at all.
-  Run as normal user produces: `-bash: ./bootstrap.bat: Permission denied`
- Run as `sudo ./bootstrap.bat clang` produces: `sudo: ./bootstrap.bat: command not found`

- Skipping the `./bootstrap.bat clang` command and executing `./b2 toolset=clang link=static threading=multi –build-dir=Build stage variant=release –layout=tagged cxxflags=-std=c++11 –with-filesystem` produces:
>`notice: could not find main target –with-filesystem
notice: assuming it is a name of file to create.`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/build/property.jam:293: in validate1 from module property`
>`error: Invalid property '<–layout>tagged': unknown feature '–layout’.`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/build/property.jam:302: in property.validate from module property`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/build/build-request.jam:228: in convert-command-line-element from module build-request`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/build/build-request.jam:179: in build-request.convert-command-line-elements from module build-request`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/build-system.jam:691: in load from module build-system`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/kernel/modules.jam:295: in import from module modules`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module`
>`/Users/kevin/tudatBundle/boost/build/boost_1_64_0/boost-build.jam:17: in module scope from module`

**Comment by magnific0** [comment]
Hi @transferorbit 

Thanks for reporting this.

- The proper bootstrap command for *NIX systems is
        ```./bootstrap.sh –with-toolset=gcc``` or ```clang```
    The ```.bat``` file is reserved for Windows. See also the [Boost troubleshooting guide](http://tudat.tudelft.nl/installation/troubleshooting/compilingBoostManually.html)
- Tudat creates two boost related logs files: ```build_bootstrap.log``` and ```build_b2.log``` which are located in the ```tudatBundle/boost/build/boost_1_64_0/``` folder. Can you upload them here?

Regards,

Jacco

**Comment by transferorbit** [comment]
Neither of those log files exist in that directory or the whole tudatBundle directory. Only the following files show up there:
[ls.txt](https://github.com/Tudat/tudatBundle/files/1671204/ls.txt)

**Comment by magnific0** [comment]
My apologies, the linked guide (which you also already linked) gives both Windows and *NIX commands without differentiating between them. Steps 5.1 and 6.1 are for Linux and Mac. 5.2 and 6.2 for Windows.

**Comment by magnific0** [comment]
> Neither of those log files exist

I see. Can you still upload bootstrap.log?

**Comment by transferorbit** [comment]
Your command is my wish:
[bootstrap.log.txt](https://github.com/Tudat/tudatBundle/files/1671208/bootstrap.log.txt)

**Comment by transferorbit** [comment]
> My apologies, the linked guide, which you also linked gives both Windows and *NIX commands without differentiating between them. Steps 5.1 and 6.1 are for Linux and Mac. 5.2 and 6.2 for Windows.

→ NP. I thought as much and went happily on my way with 5.1 and 6.1 in the end. As you rightly point out, though, the even-more-uninitiated newbies might be caught off guard.

**Comment by magnific0** [comment]
Thanks for uploading the bootstrap log. There seems nothing out of the ordinary. In your manual b2 attempt I notice that you use ```-with-filesystem```. The proper argument should be ```--with-filesystem```, note the double dash. Another miss in our documentation I'm afraid.

Can you comment out the following lines and try again with the automated Tudat boost build?
https://github.com/Tudat/tudatBundle/blob/master/external/CMake/add_boost.cmake#L319-L321

Thanks!

**Comment by transferorbit** [comment]
Attempted the TUDAT boost build in QT again, and while it made it further along, configuration fails again.
- Here is the log of _General Messages_
[QT - boost configuration issues #27 - general messages.txt](https://github.com/Tudat/tudatBundle/files/1671251/QT.-.boost.configuration.issues.27.-.general.messages.txt)

- Here is an image of the _Issues_ generated
<img width="889" alt="qt - boost configuration issues 27 - issues list" src="https://user-images.githubusercontent.com/19568006/35484181-bbd9968a-044c-11e8-9134-898f82179f16.png">
Other log files:

[bootstrap-log.txt](https://github.com/Tudat/tudatBundle/files/1671255/bootstrap-log.txt)
[build_b2.log.txt](https://github.com/Tudat/tudatBundle/files/1671262/build_b2.log.txt)
[build_bootstrap.log.txt](https://github.com/Tudat/tudatBundle/files/1671264/build_bootstrap.log.txt)

(Apologies for the staccato posting. 😊)

**Comment by transferorbit** [comment]
Odd that in the _build_bootstrap.log_ the argument shows up as `./bootstrap.sh;--with-toolset=clang`.
It seems that that semi-colon ought not to be there, but that might not be the problem.

**Comment by DominicDirkx** [comment]
@transferorbit 

How long does Qt take on the line

  ./b2;--user-config=cmake-config.jam;link=static,shared;threading=multi;--build-dir=Build;stage;architecture=combined;address-model=32_64;variant=release;--layout=tagged;toolset=clang;--with-filesystem;--with-system;--with-thread;--with-regex;--with-date_time;--with-test

during the opening of the CMakeLists.txt?

It seems to be complaining that it cannot copy any files from:

/Users/kevin/tudatBundle/boost/build/boost_1_64_0_Clang_9_0_0_9000039/stage

Is there any stage/lib sub-directory in your boost directory? If so, does it have any of the .a files in it?

**Comment by transferorbit** [comment]
I have subsequently tried to build boost again manually (using the source from sourceforge), which results in a different error:
When running `./boost_1_64_0/bootstrap.sh --with-toolset=clang`

The following errors are written to the console:
> `Building Boost.Build engine with toolset clang... `
> `Failed to build Boost.Build build engine`
> `Consult 'bootstrap.log' for more details`

And the resulting bootstap.log contains only the following:
> `./boost_1_64_0/bootstrap.sh: line 226: cd: ./tools/build/src/engine: No such file or directory`

**Comment by DominicDirkx** [comment]
After some googling, it seems like this issue sometimes occurs when the boost submodules have not been initialized. However, since we download the whole thing as a zip file, this shouldn't be a problem. The build/src/engine/ file that it seems to be complaining about is here for me:

![image](https://user-images.githubusercontent.com/5039068/35485275-797f4c4c-045d-11e8-920d-77a8394f82c8.png)

is it missing for you?

@transferorbit  Just to make sure that there isn't any pollution from multiple build attempts could you
- Delete your boost directory
- Delete your CMakeLists.txt.user file in tudatBundle
- Delete your tudat build folder (if it exists)

And try running the CMakeLists.txt file again? Does it download the boost zip file automatically, and then spend any time building boost (b2 command)? If you could post the full CMake output, hopefully that can shed some light on this.

**Comment by transferorbit** [comment]
@DominicDirkx 
It flies past the `./b2 ...` in the blink of an eye. That portion of the configuration shows this:
> `Build boost (note that this may take a while, please sit back)`
> `./b2;--user-config=cmake-config.jam;link=static,shared;threading=multi;--build-dir=Build;stage;architecture=combined;address-model=32_64;variant=release;--layout=tagged;toolset=clang;--with-filesystem;--with-system;--with-thread;--with-regex;--with-date_time;--with-test`
> `CMake Error at external/CMake/add_boost.cmake:428 (file):`
> ` file COPY cannot find`
> ` "/Users/kevin/tudatBundle/boost/build/boost_1_64_0_Clang_9_0_0_9000039/stage”.`
> `Call Stack (most recent call first):`
> `CMakeLists.txt:61 (include)`
>
> `Building CSpice from within TudatBundle.`
> [and so on ...]

There is also no `stage/lib` under `/Users/kevin/tudatBundle/boost/build/boost_1_64_0_Clang_9_0_0_9000039/`

**Comment by DominicDirkx** [comment]
Very curious, that either means that it thinks it's already built boost, or that it can't/thinks it doesn't need to.

Just for my understanding: it was working fine before with boost 1.64 right?

**Comment by transferorbit** [comment]
@DominicDirkx 
> Just for my understanding: it was working fine before with boost 1.64 right?
\> Yes, it was working with Boost 1.64 in the past.

I’ll try that clean build next...

**Comment by transferorbit** [comment]
> The build/src/engine/ file that it seems to be complaining about is here for me: [...] is it missing for you?

\> This path is now there: `tudatBundle/boost/build/boost_1_64_0_Clang_9_0_0_9000039/tools/build/src/engine/`

> @transferorbit Just to make sure that there isn't any pollution from multiple build attempts could you
> - Delete your boost directory
> - Delete your CMakeLists.txt.user file in tudatBundle
> - Delete your tudat build folder (if it exists)
> And try running the CMakeLists.txt file again?

\> Done.

> Does it download the boost zip file automatically, 

\> Yes.
> ... and then spend any time building boost (b2 command)? 

\> No. No time at all.

[Full CMake output file here.](https://github.com/Tudat/tudatBundle/files/1671475/CMake.output.-.clean.build.txt)

The _Issues_ tab in QT shows the following errors:
<img width="923" alt="screen shot 2018-01-28 at 20 17 55" src="https://user-images.githubusercontent.com/19568006/35486037-7907937c-0468-11e8-941f-915979af7869.png">

For what it’s worth, this `BOOST_ROOT`-related error looks familiar from the installation issues I was having about a year ago.

**Comment by DominicDirkx** [comment]
Strange, do you remember how we fixed it then? Let's have another look tomorrow.

Do you happen to have Boost installed on your system, it may be interfering with the add_boost script.

**Comment by magnific0** [comment]
I have added a fix to add_boost.cmake to check whether some very basic POSIX C library exists (basically check wether XCode command-line tools are installed).

I have pushed this directly to master (my apologies, my remotes were not configured properly). However, I propose to leave it there anyway. You can view the additional lines here:
https://github.com/Tudat/tudatBundle/blob/master/external/CMake/add_boost.cmake#L88-L102

@transferorbit can you check whether with this new add_boost.cmake

- cmake passes fine without throwing the fatal_error on line 98 or 100

- cmake does throw this useful new error message when xcode command-line tools are not installed. Specifically the error at 98 (targeted at Mac) and not the one at 100. And copy the output?

To uninstall XCode command line tools simply:

    rm -rf /Library/Developer/CommandLineTools

see [here](https://developer.apple.com/library/content/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_) and [here](https://stackoverflow.com/questions/27438457/xcode-6-1-how-to-uninstall-command-line-tools).
