### ISSUE TITLE
Termination condition based on specific energy

### ISSUE THREAD

**Issue by gdominguezcala** [Tudat/tudatBundle#29]
Would it be possible to create a dependent variable to use for the termination settings based on the Specific Energy of a re-entry vehicle?

It would use as inputs the altitude (h), speed (V), and some Environment parameters such as the body average radius (R) and the standard gravitational parameter (GM). The Equation could look as follows

E  = h * g + V^2 / 2

Where g could be the surface gravity, or for higher accuracy it could be computed as follows
g = GM / (R + h)^2

**Comment by DominicDirkx** [comment]
I've written the code for this and pushed it to this branch:

https://github.com/DominicDirkx/tudat/tree/EnergyTermination

see:

https://github.com/Tudat/tudat/compare/master...DominicDirkx:EnergyTermination

for differences w.r.t. master branch. The new dependent variable is called energy_wrt_reference_surface

I took the first equation, as it was easier to implement, and took the airspeed as V.

Note that I've checked that it compiles, but have not verified if the code is correct. I'm pretty confident that it is, but check manually (save altitude and airspeed, and check if you get the same energy level).
