### ISSUE TITLE
Error (Unable to find) when testing

### ISSUE THREAD

**Issue by AlvaroCT** [Tudat/tudatBundle#32]
I have got the following error while testing the libraries to start using Tudat. I have tried to compile and test them three times without success. 

My operating system is Windows 10 Pro, intel Core i7-2670QM CPU @2.2GHz and my Compiler version is Qt Creator 4.7.2.

Please find attached .txt file with Error log, compile output. 

[Error.txt](https://github.com/Tudat/tudatBundle/files/2572149/Error.txt)

**Comment by DominicDirkx** [comment]
Dear Alvaro,

Did the compilation conclude successfully for you? Could you attach the compile output when you get (without the test command),

Dominic

**Comment by AlvaroCT** [comment]
Yes, it did. It gave me some warnings messages but I thought there were not important. I am running it again because I did not save the Compile Output. Or there is any way of getting it afterwards? 

Thank you so much. 
Alvaro.

**Comment by DominicDirkx** [comment]
One small thing: could you open an issue at:

https://github.com/tudat/tudat

that's where we track most of our (install) issues. I'll close this one, and we can continue the discussion there.

I don't think the compile output gets saved, unfortunately, so youll have to rerun.
