### ISSUE TITLE
Tudat Compilation Error

### ISSUE THREAD

**Issue by lmajerustudelft** [Tudat/tudatBundle#34]
Hello, 

I have to redo the TUDAT installation on my new laptop as the other one crashed. However, during step 5 of the compilation and configuration of the tudat libraries phase, this error occurs: 
[error.txt](https://github.com/Tudat/tudatBundle/files/2596711/error.txt)

What can I do to solve this problem ? 

My laptop is 64 bits Microsoft 10. I hope that this message is clear enough, otherwise don't mind asking for more details. 

Thanks for your help, 
Louis

**Comment by DominicDirkx** [comment]
I think this is the same issue as:

https://github.com/Tudat/tudat/issues/457

**Comment by lmajerustudelft** [comment]
The solution to this problem is to desactivate the real-time scanning and firewall of the McAfee antivirus.

**Comment by DominicDirkx** [comment]
Troubleshooting guide has been updated
