### ISSUE TITLE
SPICE(KERNELVARNOTFOUND) error using Pagmo

### ISSUE THREAD

**Issue by wjhuisman** [Tudat/tudatBundle#38]
Hi,

When I am trying to run an optimization script, which uses Pagmo, I get a weird message in the application output from Spice saying
 
```
Toolkit version: N0065
 
SPICE(KERNELVARNOTFOUND) -- The Variable Was not Found in the Kernel Pool.
 
The variable BODY399_RADII could not be found in the kernel pool.
 
A traceback follows.  The name of the highest level module is first.
bodvrd_c --> BODVRD
 
Oh, by the way:  The SPICELIB error handling actions are USER-TAILORABLE.  You
can choose whether the Toolkit aborts or continues when errors occur, which
error messages to output, and where to send the output.  Please read the ERROR
"Required Reading" file, or see the routines ERRACT, ERRDEV, and ERRPRT.
```

I don't get any errors though, but also not the output I anticipated. I previously used spice in my constructor to get the radius of the Earth, but removed it after I got this message. I even tried using 
`spice_interface::clearSpiceKernels();` but that did not resolve this issue either. I am not using spice anywhere, but I still get this message. I even restarted Qt, but that did not help.

How can I get past this issue?

**Comment by DominicDirkx** [comment]
Does this error occur during the first propagation, or only for a later one? Are you loading any Spice kernels? Please post a link to your code, with specific lines where spice kernels are loaded, and when bodies are created indicated.

**Comment by wjhuisman** [comment]
I am currently working on a seperate executable that uses pagmo. In the file: [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/master/sources/deOrbitOptimization.cpp](url) I am running the optimization. In the file [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/master/problems/deOrbit.cpp](url) I am propagating a single object for a day in the fitness function, and am determining the least distance between the object and an arbitrary target. The fitness function can vary both the argumentOfPeriapsis and longitudeOfAscendingNode. In the files I use for this executable I am not using spice anywhere (except in the include file `"Tudat/InputOutput/basicInputOutput.h"`). You should have got a colaborator invite for this repo.

**Comment by DominicDirkx** [comment]
You are using default body settings, which use Spice. You need to load the Spice kernels to use these settings.

**Comment by wjhuisman** [comment]
Thank you! That fixed it!
