### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lvanderheijden** [Tudat/tudatBundle#42]
I encountered an error when compiling the code. I tried to rerun it several times but the error kept popping up.

Operating system: Windows
Cmake version: Latest Release (3.15.5)
Qt version: Qt 5.13.2

[erroroutput.txt](https://github.com/Tudat/tudatBundle/files/3835693/erroroutput.txt)

**Comment by DominicDirkx** [comment]
Hi, 

I'm afraid this is not a 'known' error, but I'm sure we'll figure it out. First, could you post a screenshot of your 'Kit' as in Step 6 of:

https://tudat.tudelft.nl/installation/setupDevWindows.html#qt-creator-mingw

If you'd like, you could come by this afternoon so we can try to fix this before the lecture tomorrow. Send me an e-mail with a time that would suit you today,

Best,

Dominic

**Comment by lvanderheijden** [comment]
![Screenshot](https://user-images.githubusercontent.com/57575472/68670945-719e2900-054e-11ea-8a29-4f89ea260e85.PNG)

**Comment by lvanderheijden** [comment]
In New CMake heb ik de stappen gevolgd die in de manual staan

**Comment by DominicDirkx** [comment]
This all looks fine, thanks for posting it. 

Could you also copy/paste the CMake output into a text file (the text under 'General Messages' in Qt)?

**Comment by lvanderheijden** [comment]
[QT_output.txt](https://github.com/Tudat/tudatBundle/files/3836071/QT_output.txt)

**Comment by DominicDirkx** [comment]
Hi,

I hope things are compiling now. Could you post the error output we just generated? Also, could you check whether your Windows is 32- or 64-bit? (see, for instance, https://www.lifewire.com/am-i-running-a-32-bit-or-64-bit-version-of-windows-2624475),

Dominic

update: this issue was (maybe) solved in a quick and dirty way by simply commenting out all usages of the 'createLightTimeCorrectionPartials' function.

**Comment by lvanderheijden** [comment]
Hi,

It compiled, thanks! Will now run the unit tests. I have 64 bit version of windows with 8 GB of RAM. 
[error2.txt](https://github.com/Tudat/tudatBundle/files/3836480/error2.txt)

Lars

**Comment by lvanderheijden** [comment]
6 tests failed, there shown in the text file. This is because we commented out the usage of  'createLightTimeCorrectionPartials', right? 
[Failedtests.txt](https://github.com/Tudat/tudatBundle/files/3836679/Failedtests.txt)

**Comment by DominicDirkx** [comment]
Hi Lars,

Yes, all 6 failures would seem to be due to the removal of createLightTimeCorrectionPartials. Regardless, none of the observation models will be used in AE4868/AE4866, so yoiu can ow safely use Tudat,

But, I still have no idea why we had to comment these lines out....

Best,

Dominic
