### ISSUE TITLE
Project Configuration error/warning.

### ISSUE THREAD

**Issue by sai1296** [Tudat/tudatBundle#43]
I tried to follow steps as per the tutorial and I am facing these warnings in the general messages tab.

[Configuration - Output.txt](https://github.com/Tudat/tudatBundle/files/3851133/Configuration.-.Output.txt)

**Comment by transferorbit** [comment]
If tudat compiled correctly and the unit tests completed successfully, then you should be able to continue without issues for the near future.

However, I have some questions:

- Where did you install (what is the path to) the tudatBundle on your computer?
- Did you, when installing tudat, pay attention to the following Warning:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/19568006/68943743-53cdff80-07ac-11ea-9b27-026cbf88cbd5.png">

[on this page](http://tudat.tudelft.nl/installation/downloadTudatBundle/index.html) of the tudat installation guide?

If you installed the tudatBundle at a much lower level in your directory tree, you might end up with errors in the future when adding your own, new applications to tudat.

**Comment by sai1296** [comment]
Initially i didn't install it in the root directory as specified, bu then i removed the whole tudatBundle and repeated the cloning process again to the root directory.
Still I faced the issue.
I'll try to redo the whole process again and I'll update the status of compilation and installation.

**Comment by sai1296** [comment]
I did the whole installation process again and I placed it under the root directory directly as per the instruction. Still, I am getting the same warnings and CMake Project was parsed successfully again.


[Configuration - Output.txt](https://github.com/Tudat/tudatBundle/files/3854265/Configuration.-.Output.txt)

**Comment by DominicDirkx** [comment]
Did you have a look at this sentence in Kevin's original reply:

"If tudat compiled correctly and the unit tests completed successfully, then you should be able to continue without issues for the near future."

I see lots of CMake output, but nothing that is necessarily indicative of a bad installation. Try to compile, and if succesful, try to run the unit tests.

**Comment by sai1296** [comment]
I compiled and ran the unit tests and 100% of the tests passed. I hope there won't be any issues in the future.
Thanks for the help.
