### ISSUE TITLE
Issue with compiling of CMake lists

### ISSUE THREAD

**Issue by vavjagarlapudi** [Tudat/tudatBundle#44]
I had to re-install my TUDAT software and I faced an issue while compiling the CMake lists. I have tried uninstalling and re-installing the software multiple times, but I continue to face the same error. Can you please help?
[Error_message_Qt.txt](https://github.com/Tudat/tudatBundle/files/4045057/Error_message_Qt.txt)

**Comment by DominicDirkx** [comment]
I assume this was handled during the working lecture, as you mentioned your issue had been solved.
