### ISSUE TITLE
Problem with Ninja build tool "CMake was unable to find a build program corresponding to "Ninja". "

### ISSUE THREAD

**Issue by olo96** [Tudat/tudatBundle#45]
Trying to follow step 3 of TUDAT bundle compilation from the installation manual on TUDAT website, I encountered a problem with Ninja Build tool (from what I understand). I followed all the previous steps closely twice (to make sure) and the problem remains.

From the general messages prompt in QT:
"Running C:\Program Files\CMake\bin\cmake.exe C:/tudatBundle "-GCodeBlocks - Ninja" in C:\tudatBundle.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "C:/tudatBundle/CMakeFiles/CMakeOutput.log".
CMake process exited with exit code 1."

**Comment by DominicDirkx** [comment]
From the looks of you're working on Windows. I think you have some of the settings shown here:

http://tudat.tudelft.nl/installation/setupDevWindows.html#qt-creator-mingw 

set incorrectly, in particular the 'CMake Generator'

**Comment by olo96** [comment]
Thank you. All issues seem to be resolved now as all the test units were passed.
