### ISSUE TITLE
Applying NLOPT to optimise global search results

### ISSUE THREAD

**Issue by jasperwolfhagen** [Tudat/tudatBundle#46]
Dear,

I'm currently performing global optimisation procedures with the MOEAD/DE algorithm of Pagmo (multi-objective) to uncover favourable maneuvers for collision avoidance and present them in a Pareto front. My idea is to further optimise individual solutions of the Pareto front AFTER the global optimisation routine has finished. I shall combine the objectives in a single objective function and applying a local search technique (by incorporating the weights for each objective, which can be deduced from the Pareto front). 

To this end, I want to use NLOPT, but I have issues understanding the syntax. I've followed the syntax from _https://nlopt.readthedocs.io/en/latest/NLopt_C-plus-plus_Reference/_ and _https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/_ but it does not seem te find the namespace _nlopt_, please see scripts attached. 

An additional question, is the way the objective function (_fitnessSingleObjective_) is incorporated fruitful.

[Archive.zip](https://github.com/Tudat/tudatBundle/files/4280081/Archive.zip)

**Comment by DominicDirkx** [comment]
Hi Jasper,

In the latest Tudat version, NLOPT is included through the Pagmo interface. Please set USE_NLOPT to ON, and see if you can use it through there. Associated documentation on how to call it can be found on the Pagmo website.

Best,

Dominic
