### ISSUE TITLE
Applying the nrlmsise00 atmospheric model

### ISSUE THREAD

**Issue by jasperwolfhagen** [Tudat/tudatBundle#47]
Dear,

I'm trying to apply the nrlmsise00 atmospheric model. As I understood the model is simply just called by assigning it to the bodyMap entry --> Earth. See attached script DynamicsPropagator.cpp line 57 - 64. However I get an application output error that it cannot convert the date, see error.txt. I've looked at the header files and c files but do not understand what extra settings are needed.

Do you have a suggestion to overcome this issue?

[Archive.zip](https://github.com/Tudat/tudatBundle/files/4281601/Archive.zip)

**Comment by DominicDirkx** [comment]
See this previous issue, your problem would seem to be identical:

https://github.com/Tudat/tudat/issues/567
