### ISSUE TITLE
Building error when building Pagmo on remote linux server

### ISSUE THREAD

**Issue by martijnrozemeijer** [Tudat/tudatBundle#49]
Dear Dominc,

For my thesis work I like to use a remote linux server of the space department (eudoxos home3/martijn) to spread my computational work across various platforms to speed up all my simulations. I have followed the steps of the manual in http://tudat.tudelft.nl/installation/setupLinuxServer.html, however when I try to activate the pagmo library in the CMakeLists.txt I get build errors which I do not get when Pagmo is turned off in the CMakeLists.txt. I have turned off the json build to avoid getting compilations errors as is suggested in the manual. 

I have added the error message in this issue. I also added my CMakelists.txt with and without pagmo. 

I hope you are able to help me with this problem!
[errorBuild.txt](https://github.com/Tudat/tudatBundle/files/4407916/errorBuild.txt)
[CMakeListsWithPagmo.txt](https://github.com/Tudat/tudatBundle/files/4407920/CMakeListsWithPagmo.txt)
[CMakeListsWithoutPagmo.txt](https://github.com/Tudat/tudatBundle/files/4407921/CMakeListsWithoutPagmo.txt)

**Comment by elmarputs** [comment]
Dear Martijn,

I have taken a quick look at the log and CMake configuration, from which I cannot tell the underlying problem yet. Could you pull the CMakeCache.txt file from the server and upload it here? This file resides in your CMake build directory and gives a complete overview of the current CMake configuration that you use in your build.

Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

I have added the cache file in this post. 
[CMakeCache.txt](https://github.com/Tudat/tudatBundle/files/4408927/CMakeCache.txt)

**Comment by elmarputs** [comment]
Your configuration seems to be right, so my guess is that there is some kind of incompatibility between the compiler and the new Pagmo version. Could you perhaps check the GCC version on your server?
The command you would have to run is:
`gcc --version`

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

See below:

gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by elmarputs** [comment]
Hi Martijn,

Thanks for your answer. The version is quite outdated, but the Pagmo site claims that this version should still be supported. I will ask Dominic if there have been people who managed to get this combination to work on the TU Delft servers; if not, we would have to see if we can upgrade the GCC version to a newer release.

I will keep you posted,

Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

Thank you for the quick response! Let me know if anything changes. It may be that some of my paths does not correspond. See my path below: 
/usr/lib64/mpi/gcc/openmpi/bin:/home3/martijn/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin

**Comment by elmarputs** [comment]
Hi Martijn,

According to Dominic, there are multiple students who managed to get the combination of Pagmo and Tudat working on the Linux servers. Personally, I do not think that your PATH forms a problem, but given the fact that Boost is causing the trouble, I rather suspect something is off with your Boost suite.

How did you install Tudat (and Boost) on your server? (I.e., have you copied all the files to the server or have you downloaded the repository on the server itself?)

Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

I followed the steps of: http://tudat.tudelft.nl/installation/setupLinuxServer.html . So I cloned the current tudat version in my folder using "git clone https://github.com/tudat/tudatBundle.git"  and updated all the modules using "git submodule update --init --recursive" in tudatBundle. From there on I ran the CMakeLists.txt  with "cmake CMakeLists.txt" with Pagmo turned on in this CMakelists.txt. I then built all the libraries using "cmake --build . --target all -- -j14". I have not copied any files on the server yet to make sure the clean built was working properly. 

I have deleted all my tudat directories on eudoxos a couple of times and repeated the installing process with pagmo turned on and off. The strange thing is that tudat compiles and runs standard applications fine with pagmo turned off, however with pagmo turned on it does not.

Martijn

**Comment by elmarputs** [comment]
**Edit: perhaps try to run the build without the j14 option first, to see if that causes the trouble. Sometimes the build dependencies are not figured out properly by CMake**

Thanks for the clear explanation. In this case, Boost should be freshly compiled on the server. 
I do see, however, that CMake does not detect a 'Release' version of the boost libraries, which should be happening (I just checked it on my own Linux system). In the process, I am following the wiki and I see that the build files are placed among the source files, which could be the reason that things get messed up. For now, I think it is best to remove the tudatBundle (again, I am sorry) and reclone it on the server. Then initialize all submodules, but do not yet run CMake.

Let me know when you have performed these steps!
Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

I have removed the tudatBundle, cloned it again and initialized all submodules.

**Comment by elmarputs** [comment]
Hi Martijn,

Perfect! Now I would advise doing the following:

1. Go up one directory by using `cd ..` (so you are now in the folder containing tudatBundle/)
2. Create a build directory there with `mkdir tudat-build`
3. Go into that directory `cd tudat-build/`
4. Run CMake there `cmake ../tudatBundle/CMakeLists.txt -DUSE_PAGMO=ON -DUSE_JSON=OFF` (specify other options if necessary)
_I.e., do not change the CMakeLists.txt file, but rather specify the options on the command line._

You can then check the CMakeCache in the build directory to see if the options have been properly set. Could you upload that file here?

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

Using your method no builds were constructed in tudat-build as is demonstrated by following message:
"Build files have been written to: /home3/martijn/thesiswork/tudatBundle"

Is there a way to force the build to happen in tudat-build? I have now tried you method twice.

**Comment by elmarputs** [comment]
Hmm, that is very strange, as this should work. What you could try is to again (I am very sorry) remove the tudatbundle tree + build folder and follow the same steps. Make sure you only execute CMake in the build folder, and remove the /CMakeLists.txt as it is unnecessary and may (?) cause the build to happen in the source folder anyway; so execute the following command:
`tudat-build$ cmake ../tudatBundle -DUSE_PAGMO=ON -DUSE_JSON=OFF`

Elmar

**Comment by elmarputs** [comment]
Sorry, maybe my post was a little confusing. What I mean with 'remove the /CMakeLists.txt' is to remove it from the command, so that you execute the command I put in the post.

Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

The method you just described worked for the build directory. See my CMakeCache.txt file attached in this comment.
[CMakeCache.txt](https://github.com/Tudat/tudatBundle/files/4415226/CMakeCache.txt)

**Comment by elmarputs** [comment]
Good to hear! Now you can build **from within the build directory** by running:
`cmake --build . --target all -- -jxx` (with xx the number of processes to run simultaneously)
Hopefully, the build will now complete successfully.

Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

I still get build errors when I build tudat in the build directory (tudat-build). However more errors have appeared. The error output can be found in the attachment of this post. 
[errorbuildintudat-build.txt](https://github.com/Tudat/tudatBundle/files/4415419/errorbuildintudat-build.txt)

**Comment by DominicDirkx** [comment]
Hi Martijn,

It's very odd that this is not working for you.... Try the following, to prevent the build directory and source directory from overlapping. 
- Delete your source and build directory entirely (clean slate)
- Clone Tudat: git clone https://github.com/tudat/tudatBundle.git" 
- Initial submodules git submodule update --init --recursive

Perform the three steps Elmar wrote:

1) Go up one directory by using cd .. (so you are now in the folder containing tudatBundle/)
2) Create a build directory there with mkdir tudat-build
3) Go into that directory cd tudat-build/ 

Then, use:

cmake -S ../tudatBundle/

And please post the output in a text file here,

Best,

Dominic

**Comment by martijnrozemeijer** [comment]
Hi Dominic,

I have removed the source and build directory and performed the steps. Apparently a new error has arisen as well that causes the cmake not to run as well (see CMakeOutput.log). This has not happened before. I believe the boost version has been changed yesterday on the eudoxos machine. I have added the message I got as well in errormessage.txt. 

[errormessage.txt](https://github.com/Tudat/tudatBundle/files/4420646/errormessage.txt).  

CMakeOutput.log](https://github.com/Tudat/tudatBundle/files/4420617/CMakeOutput.log)

**Comment by DominicDirkx** [comment]
Hi Martijn,
This is not a change in Boost version, but indicates that boost could not be downloaded. Possibly the boost server was down. You can try again later.

Since it's very difficult for us to really see the steps you are taking, and it's difficult to invite you to our office so we can have a look, I recommend the following: contact one of the other students who have recently(-ish) started using Tudat on the server, and locally copy their code. This should allow you to get started,

Dominic

**Comment by martijnrozemeijer** [comment]
Hi Dominic and Elmar, 

Sorry for the late reaction. I have contacted a student who is now performing his computations on Eudoxos with tudat. 

I have removed tudat again, tried the steps again and added a message possibility in tudatbundle/external/add_boost.cmake that outputs a message of the link of the website for the download of boost and its hash. Apparently the website and hash check out with what is posted on the website as can be seen in the outputlog (outputEudoxos.txt). I am not sure what is going wrong in the cmake. 

[outputEudoxosBoost.txt](https://github.com/Tudat/tudatBundle/files/4451430/outputEudoxosBoost.txt)
.

**Comment by martijnrozemeijer** [comment]
Hi Dominic and Elmar,

Sorry for the late reply. I have reached out to someone who is currently using tudat on a remote TU Delft linux server however he is not running pagmo. I have installed tudat on a different remote linux server with the required steps seen below. Trying installing tudat on this different remote server worked! I ran the cmake file with pagmo turned on and json turned off (see CMakeLists.txt) in the build directory with "cmake -S ../tudatBundle/" and got the output found in outputThales.txt. I got warnings on regarding missing boost dependencies. I also uploaded the cache under CMakeCache.txt. 

When building the directory with "cmake cmake --build . --target all -- -j14" a problem was found with boost (see output in buildoutputThales.txt).  I also ran the cmake and built tudat in the build directory with pagmo turned off and this caused no errors in the building process and all unit tests passed. 

Hopefully this clear things up!

Kind regards,

Martijn


[outputThales.txt](https://github.com/Tudat/tudatBundle/files/4452292/outputThales.txt)
[CMakeLists.txt](https://github.com/Tudat/tudatBundle/files/4452310/CMakeLists.txt)
[buildoutputThales.txt](https://github.com/Tudat/tudatBundle/files/4452318/buildoutputThales.txt)
[CMakeCache.txt](https://github.com/Tudat/tudatBundle/files/4452384/CMakeCache.txt)


> Hi Martijn,
> 
> It's very odd that this is not working for you.... Try the following, to prevent the build directory and source directory from overlapping.
> 
> * Delete your source and build directory entirely (clean slate)
> * Clone Tudat: git clone https://github.com/tudat/tudatBundle.git"
> * Initial submodules git submodule update --init --recursive
> 
> Perform the three steps Elmar wrote:
> 
> 1. Go up one directory by using cd .. (so you are now in the folder containing tudatBundle/)
> 2. Create a build directory there with mkdir tudat-build
> 3. Go into that directory cd tudat-build/
> 
> Then, use:
> 
> cmake -S ../tudatBundle/
> 
> And please post the output in a text file here,
> 
> Best,
> 
> Dominic

**Comment by elmarputs** [comment]
Hi Martijn,

Could you remove the boost folder in the Tudat bundle and then rerun CMake in the build directory?
This way, CMake is forced to download Boost again and compile all required Boost libraries. It seems that some crucial libraries required by Pagmo are missing, which means that either Boost or CMake is rocking the boat here.

Secondly, could you run `cmake --version` in your remote terminal and post the output here? Perhaps the CMake version is also outdated, causing the issues.

Kind regards,
Elmar

**Comment by martijnrozemeijer** [comment]
Hi Elmar,

I have followed your instructions with regards to boost and ran the cmake command again. The output of messages can be found in outputThalesMessagesCMake.txt and the current cache can be found in CMakeCache.txt. I also the version command and it gave the following output:

martijn/thesis> cd build
thesis/build> cmake --version
cmake version 3.10.2

I did not run the build process yet.

Kind regards,

Martijn
[outputThalesMessagesCMake.txt](https://github.com/Tudat/tudatBundle/files/4461553/outputThalesMessagesCMake.txt)

[CMakeCache.txt](https://github.com/Tudat/tudatBundle/files/4461550/CMakeCache.txt)

**Comment by martijnrozemeijer** [comment]
Hi Dominic and Elmar,

I have built tudat library with pagmo turned on and the build process was successful. All 303 unit tests passed and I ran a library example which converged properly. The server was updated today by the administrator to opensuse 15.0 with gnu version 7, clang version 5 and cmake version 3.10. 

Thank you for all the help!

Kind regards,

Martijn
