### ISSUE TITLE
Installation: build files created at wrong location [mac]

### ISSUE THREAD

**Issue by transferorbit** [Tudat/tudatBundle#52]
During installation, §3 [_Compile and Test Tudat Libraries_](http://tudat.tudelft.nl/installation/configureTudatLibraries.html#compile-and-test-tudat-libraries), during step 3 _Configure Project_, the build files are not written to the `/Users/<home>/build-tudatBundle...` path as desired, but to a temporary folder:
```
Build files have been written to: /private/var/folders/8g/hn5l8vp10cl1m5xp41h0rpgm0000gn/T/QtCreator-aCwOJi/qtc-cmake-VuBQwONw
```
This was a clean install with no installation defaults altered.

It appears that _Qt_ is currently not creating the build folder path if it does not already exist but instead builds in the path mentioned above; I’m testing this hypothesis now.

This appears similar to the following [Qt bug report](https://bugreports.qt.io/browse/QTCREATORBUG-16794).

**General messages output**
[installation_build_path_error.txt](https://github.com/Tudat/tudatBundle/files/4579390/installation_build_path_error.txt)

**Comment by transferorbit** [comment]
This is possibly a work-around rather than a fix (which may be a _Qt_ bug, see above):

* Manually create the build folder (eg. at the path shown below) before opening `CMakeLists.txt`; then
* when confronted with the _Configure Project_ dialog, adjust the build folder name(s) to match.
```
Build files are written to: /Users/<home>/build-tudatBundle
```

This leads to successful configuration, compilation, and unit tests.

**General messages output**
[installation_build_path_error_fixed.txt](https://github.com/Tudat/tudatBundle/files/4579675/installation_build_path_error_fixed.txt)

**Comment by transferorbit** [comment]
Separate issue but, for what it’s worth, _Qt_ is still defaulting to building in _Debug_ mode rather than _Release_. 🙄

**Comment by transferorbit** [comment]
For posterity, if you run into this there is a setting in _Preferences_ > _Kits_ > _CMake_ to enable _Auto-create build directories_.

In previous versions of _QT_ this was enabled by default. Not so anymore apparently.

<img width="957" alt="Screenshot - auto-create build directories" src="https://user-images.githubusercontent.com/19568006/81314228-28f0a400-9089-11ea-8505-7ac0973fc12c.png">

**Comment by DominicDirkx** [comment]
Sigh.... Why do they have to change these defaults....?
