### ISSUE TITLE
CMake Policy CMP0045 is not set: Error on non-existent target in get_target_property.

### ISSUE THREAD

**Issue by piofel** [Tudat/tudatBundle#59]
Running /home/piotr/Qt/Tools/CMake/bin/cmake -S /home/piotr/cpp_libraries/tudatBundle -B /home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Debug -GNinja -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_PROJECT_INCLUDE_BEFORE:PATH=/home/piotr/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake -DQT_QMAKE_EXECUTABLE:STRING=/home/piotr/Qt/6.2.2/gcc_64/bin/qmake -DCMAKE_PREFIX_PATH:STRING=/home/piotr/Qt/6.2.2/gcc_64 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ in /home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Debug.
CMake Deprecation Warning at CMakeLists.txt:12 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /home/piotr/cpp_libraries/tudatBundle
-- BOOST: Using gnu.
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Downloading boost 1.64.0 to /home/piotr/cpp_libraries/tudatBundle/boost/build
-- [download 100% complete]
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Extracting boost 1.64.0 to /home/piotr/cpp_libraries/tudatBundle/boost/build/boost_unzip
-- Building b2 (bjam)
--   ./bootstrap.sh;--with-toolset=gcc
-- Build boost (note that this may take a while, please sit back)
--   ./b2;--user-config=cmake-config.jam;link=static,shared;threading=multi;--build-dir=Build;stage;-sNO_BZIP2=1;variant=release;--layout=tagged;toolset=gcc;--with-filesystem;--with-system;--with-regex;--with-date_time;--with-test;--with-thread
CMake Deprecation Warning at cspice/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Building CSpice from within TudatBundle.
-- WARNING: building debug version!
CMake Deprecation Warning at nrlmsise-00/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Building NRLMSISE00 from within TudatBundle.
-- WARNING: building debug version!
CMake Deprecation Warning at sofa/src/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- WARNING: building debug version!
CMake Deprecation Warning at tudat/Tudat/CMakeLists.txt:11 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- << Tudat (Debug - part of TudatBundle) >>
-- CMake Module path(s): /home/piotr/cpp_libraries/tudatBundle/external/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake
-- Using gnucxx compiler.
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Success
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor -fPIC.
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Found Boost: /home/piotr/cpp_libraries/tudatBundle/boost (found suitable version "1.64.0", minimum required is "1.45.0") found components: date_time system unit_test_framework filesystem regex 
-- SPICE enabled!
-- SPICE_LIBRARIES: cspice
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SPICE) does
  not match the name of the calling package (Spice).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSpice.cmake:55 (find_package_handle_standard_args)
  tudat/Tudat/CMakeLists.txt:162 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found SPICE: /home/piotr/cpp_libraries/tudatBundle/cspice/include/../..  
-- JSON enabled!
-- Found nlohmann_json: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.10.2") 
-- SOFA enabled!
CMake Error at tudat/Tudat/CMakeLists.txt:189 (include_directories):
  include_directories given empty-string as include directory.

-- Sofa found in: /home/piotr/cpp_libraries/tudatBundle/sofa/src
-- Found SOFA: /home/piotr/cpp_libraries/tudatBundle/sofa/src/../..  
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SOFA) does
  not match the name of the calling package (Sofa).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSofa.cmake:39 (find_package_handle_standard_args)
  tudat/Tudat/CMakeLists.txt:212 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- Found NRLMSISE00: /home/piotr/cpp_libraries/tudatBundle/nrlmsise-00  
-- PAGMO disabled!
-- GSL disabled!
-- Extended precision propagation disabled!
-- SPICE enabled!
-- SPICE enabled!
CMake Warning (dev) at tudat/Tudat/Astrodynamics/CMakeLists.txt:76 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target
  "tudat_low_thrust_trajectories".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeLists.txt:11 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- << SatellitePropagatorExamples (Debug - part of TudatBundle) >>
-- CMake Module path(s): /home/piotr/cpp_libraries/tudatBundle/external/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake;/home/piotr/cpp_libraries/tudatBundle/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeModules
-- Using gnucxx compiler.
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor -fPIC.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /home/piotr/cpp_libraries/tudatBundle/boost (found suitable version "1.64.0", minimum required is "1.55.0") found components: thread date_time system unit_test_framework filesystem regex chrono missing components: atomic
-- Found Tudat: /home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/.. (Required is at least version "2.0") 
-- Relative path to Tudat found: /tudat/Tudat
-- SPICE_LIBRARIES: cspice
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SPICE) does
  not match the name of the calling package (Spice).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSpice.cmake:55 (find_package_handle_standard_args)
  tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeLists.txt:131 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- SPICE enabled!
-- << TemplateApplication (Debug - part of TudatBundle) >>
-- CMake Module path(s): /home/piotr/cpp_libraries/tudatBundle/external/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake;/home/piotr/cpp_libraries/tudatBundle/tudatExampleApplications/templateApplication/TemplateApplication/CMakeModules
-- Using gnucxx compiler.
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor -fPIC.
CMake Deprecation Warning at tudatExampleApplications/templateApplication/TemplateApplication/CMakeLists.txt:11 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found Boost: /home/piotr/cpp_libraries/tudatBundle/boost (found suitable version "1.64.0", minimum required is "1.45.0") found components: thread date_time system unit_test_framework filesystem regex chrono missing components: atomic
-- Relative path to Tudat found: /tudat/Tudat
-- SPICE_LIBRARIES: cspice
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SPICE) does
  not match the name of the calling package (Spice).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSpice.cmake:55 (find_package_handle_standard_args)
  tudatExampleApplications/templateApplication/TemplateApplication/CMakeLists.txt:131 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- SPICE enabled!
-- Configuring incomplete, errors occurred!
See also "/home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Debug/CMakeFiles/CMakeOutput.log".
See also "/home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Debug/CMakeFiles/CMakeError.log".
CMake process exited with exit code 1.

Elapsed time: 02:41.

Running /home/piotr/Qt/Tools/CMake/bin/cmake -S /home/piotr/cpp_libraries/tudatBundle -B /home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Release -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PROJECT_INCLUDE_BEFORE:PATH=/home/piotr/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake -DQT_QMAKE_EXECUTABLE:STRING=/home/piotr/Qt/6.2.2/gcc_64/bin/qmake -DCMAKE_PREFIX_PATH:STRING=/home/piotr/Qt/6.2.2/gcc_64 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ in /home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Release.
CMake Deprecation Warning at CMakeLists.txt:12 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /home/piotr/cpp_libraries/tudatBundle
-- BOOST: Using gnu.
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Boost was already build on system
CMake Deprecation Warning at cspice/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Building CSpice from within TudatBundle.
-- WARNING: building release version!
CMake Deprecation Warning at nrlmsise-00/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Building NRLMSISE00 from within TudatBundle.
-- WARNING: building release version!
CMake Deprecation Warning at sofa/src/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- WARNING: building release version!
CMake Deprecation Warning at tudat/Tudat/CMakeLists.txt:11 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- << Tudat (Release - part of TudatBundle) >>
-- CMake Module path(s): /home/piotr/cpp_libraries/tudatBundle/external/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake
-- Using gnucxx compiler.
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Success
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor -fPIC.
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Found Boost: /home/piotr/cpp_libraries/tudatBundle/boost (found suitable version "1.64.0", minimum required is "1.45.0") found components: date_time system unit_test_framework filesystem regex 
-- SPICE enabled!
-- SPICE_LIBRARIES: cspice
-- Found SPICE: /home/piotr/cpp_libraries/tudatBundle/cspice/include/../..  
-- JSON enabled!
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SPICE) does
  not match the name of the calling package (Spice).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSpice.cmake:55 (find_package_handle_standard_args)
  tudat/Tudat/CMakeLists.txt:162 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found nlohmann_json: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.10.2") 
-- SOFA enabled!
-- Sofa found in: /home/piotr/cpp_libraries/tudatBundle/sofa/src
-- Found SOFA: /home/piotr/cpp_libraries/tudatBundle/sofa/src/../..  
-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- Found NRLMSISE00: /home/piotr/cpp_libraries/tudatBundle/nrlmsise-00  
-- PAGMO disabled!
-- GSL disabled!
-- Extended precision propagation disabled!
CMake Error at tudat/Tudat/CMakeLists.txt:189 (include_directories):
  include_directories given empty-string as include directory.

CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SOFA) does
  not match the name of the calling package (Sofa).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSofa.cmake:39 (find_package_handle_standard_args)
  tudat/Tudat/CMakeLists.txt:212 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- SPICE enabled!
-- SPICE enabled!
CMake Warning (dev) at tudat/Tudat/Astrodynamics/CMakeLists.txt:76 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target
  "tudat_low_thrust_trajectories".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeLists.txt:11 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- << SatellitePropagatorExamples (Release - part of TudatBundle) >>
-- CMake Module path(s): /home/piotr/cpp_libraries/tudatBundle/external/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake;/home/piotr/cpp_libraries/tudatBundle/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeModules
-- Using gnucxx compiler.
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor -fPIC.
-- Found Threads: TRUE  
-- Found Boost: /home/piotr/cpp_libraries/tudatBundle/boost (found suitable version "1.64.0", minimum required is "1.55.0") found components: thread date_time system unit_test_framework filesystem regex chrono missing components: atomic
-- Found Tudat: /home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/.. (Required is at least version "2.0") 
-- Relative path to Tudat found: /tudat/Tudat
-- SPICE_LIBRARIES: cspice
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SPICE) does
  not match the name of the calling package (Spice).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSpice.cmake:55 (find_package_handle_standard_args)
  tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeLists.txt:131 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- SPICE enabled!
CMake Deprecation Warning at tudatExampleApplications/templateApplication/TemplateApplication/CMakeLists.txt:11 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- << TemplateApplication (Release - part of TudatBundle) >>
-- CMake Module path(s): /home/piotr/cpp_libraries/tudatBundle/external/CMake;/home/piotr/cpp_libraries/tudatBundle/tudat/Tudat/External/CMake;/home/piotr/cpp_libraries/tudatBundle/tudatExampleApplications/templateApplication/TemplateApplication/CMakeModules
-- Using gnucxx compiler.
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor -fPIC.
-- Found Boost: /home/piotr/cpp_libraries/tudatBundle/boost (found suitable version "1.64.0", minimum required is "1.45.0") found components: thread date_time system unit_test_framework filesystem regex chrono missing components: atomic
-- Relative path to Tudat found: /tudat/Tudat
-- SPICE_LIBRARIES: cspice
CMake Warning (dev) at /home/piotr/Qt/Tools/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SPICE) does
  not match the name of the calling package (Spice).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/CMake/FindSpice.cmake:55 (find_package_handle_standard_args)
  tudatExampleApplications/templateApplication/TemplateApplication/CMakeLists.txt:131 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: nrlmsise00
-- SPICE enabled!
-- Configuring incomplete, errors occurred!
See also "/home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Release/CMakeFiles/CMakeOutput.log".
See also "/home/piotr/cpp_libraries/build-tudatBundle-Desktop_Qt_6_2_2_GCC_64bit-Release/CMakeFiles/CMakeError.log".
CMake process exited with exit code 1.

Elapsed time: 00:01.

**Comment by DominicDirkx** [comment]
Dear Piotr, we have some time ago moved to a new setup for tudat, using a conda package and a python interface. See this website:

https://tudat-space.readthedocs.io/en/latest/

for more details,

Best, Dominic

**Comment by piofel** [comment]
Dear Dominic, I am aware of that, but I need the C++ version for my application. Anyway, thank you for such a quick response! Best regards,Piotr13.01.2022, 12:49, "DominicDirkx" ***@***.***>:
Dear Piotr, we have some time ago moved to a new setup for tudat, using a conda package and a python interface. See this website:
https://tudat-space.readthedocs.io/en/latest/
for more details,
Best, Dominic

**Comment by DominicDirkx** [comment]
Hi Piotr, don't worry, we haven't given up on the C++ interface! In our new setup, it is still available, although there are some changes w.r.t. the old version. If you use our new tudat bundle, you can use tudat in a similar way as before. See here for instructions:

https://github.com/tudat-team/tudat-bundle#setup

In step 3, switch tudat (and tudatpy) to the develop branch. Would this suffice for you, or do you need a tudat version that is compatible with older tudat applications?

Best,

Dominic

**Comment by piofel** [comment]
It seems that this is what I need, I do not need the old Tudat. Thank you very much!
Kind regards,
Piotr
