### ISSUE TITLE
Changing submodules

### ISSUE THREAD

**Issue by Reneh107** [Tudat/tudatBundle#6]
If you have the TudatBundle already built and you want to use other libraries for example JSON, it is difficult.

Changing the option USE_JSONCPP to ON doesn't work, because the option isn't changed in the CMakeCache.txt . Even if you change the option in the Cache file, it doesn't build the library. 

Maybe the CmakeList can be updated to check if the option is changed w.r.t. the cache? And if it is changed everything that prevents it from building should be reset?

I now just build JSONCPP seperately and made the lib folder. What needs to be changed such that the bundle will build JSONCPP ?

**Comment by magnific0** [comment]
Hi @Reneh107, I have investigated this problem and it seems at least one variable naming error was causing troubles. This has been fixed now.

My procedure of enabling features after the fact is:
1. Edit the top-level CMakeLists.txt
2. Remove CMakeCache.txt from the build directory
3. Rerun cmake
4. Rebuild

Note that the build was incremental only for me (example + library). If you do experience a complete rebuild, this is unwanted, but this is a seperate issue (and likely much more difficult).
